language: node_js
node_js:
- 16.20.2
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # MATTERMOST_HOOK_URL
  - secure: X6p+MfhrRwz+4AeJon7PPbp/Fe46ow43GyxyjKvxOdZJCzm7qc+ecTaH7tEaHdAoPhVrDLTCAmQWLQnFnL1dQAGRpHryvVv03ij8O0/c1PWAcaSAD3IaYs0QmuqtGG8X6AQOb5ol4TNPYfAZNhqr+wPojmBrgN/KLbVf7kEd7KfQrgy9jAA2hxGl1qLY2xshzxb845cMVdb2uA1sad08gz3mlYeW22G49GDiznELC0LGRr9huyrwVTzpBiVk1e4jBus3vC2t+vdzOrNPyNCOqyEC1/X3/ZqTQjlHJ6s6LiEpdLsZLsM2vk6zhz5jwnbw8qEerA0zw6Nh2w576TR58ijXQz7zhr5Q2EJ80CYqfRmzVdbBLp7yLkopuVGfpbAlm0Wl68yV2ETOK4L2ApVwC6iKzXLaGCG2494bvUl6htWhXVAczKkjdezF2/Y9p/ttxnwqO7wQjz+Qb2pB4vrmLXy7NxLzAK6RNxpu4M5qXTbQc/XlqKX3rcj8WryXZrWV9if2kAkgp3UeFApUEGFm7RkHY2wOofRlaQtYhTrfVjQ6uNOqo+r2ihwne3VtF1L6aKXRu5nIl+o5ha59D71xhvTqHBe4ogYIysKA/fpyDckWbnDF6/MCorFD4VXRVnEKTzgmz8QSWDaRW0hBKSWG+Uw8CtwHfK6GeWekKKpevag=
  # REGISTRY_TOKEN slug=gaztarifreglemente editor=cozy space=cozy_ccc
  - secure: rS2CWeSlQ5COSmxae9RshVJhl7oGEiofLYXwtC0aQEXRxIUujp1z1xzvgkyAAiUXPAWIwgq2TWdWtVlOXvc8E0YhYUrICv2nzcKuDaDsHTAIDGJvIr25Uxhiy2PY+cu3V7NSeJz96vrzTbFBSH/vxj2tZz2Yg6sVd7dqK9PoCHuSvzLSSkLQhuOcKdvluKB6BTdoW489l+j1LgJQJmbK6qAJAIE5xvB/7+lyJCNeFMTjweaNqabQgTDf0qNitaL9bBy5ZpXhwOxLuyRJA702WVUeHiS5hHFz6f+bD53MW8J1EibMUiMNOaHqHK81s0GfMmli/zngjpDI8tYkeSu/itLWFC9TPRVB11aYy+lk+oZQd5VXNk1bIR4OAIafnJIrxIk4PRApVOJD2C6za/Ml1i1OdGl8xcc81+/lHTLPbS6uGV5c6jk+Zaft+BPRupiupoAcwxXrm6Rp1He3SYq2+gyxZB4HLPPh1eIR9pl3K3GjiUO1f+ww2nNOp3TOyshQHWcqAYv7bVb+6+rmZbC20B4qguZJ3WgnmgitrdmfdNg0mJf74ctB8xrCuR2q25vilnVhZY7LWSgYzmESwPdIXbBSbPRBv0I6++iUVW/dzpR/Oil5n5kRMKLKuWRS7ugo3DASzBBecx/rftHNSIf8oW8V57pdDoDKT4WIpHS99zM=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --space cozy_ccc
  on:
    branch:
    - master
    - main
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
    --space cozy_ccc
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- if [[ -f /tmp/github_deploy_key ]]; then chmod 600 /tmp/github_deploy_key; fi
- if [[ -f /tmp/github_deploy_key ]]; then ssh-add /tmp/github_deploy_key; fi
after_deploy:
- rm -f /tmp/github_deploy_key
- ssh-add -D
