language: node_js
node_js:
- 16.20.2
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # MATTERMOST_HOOK_URL
  - secure: X6p+MfhrRwz+4AeJon7PPbp/Fe46ow43GyxyjKvxOdZJCzm7qc+ecTaH7tEaHdAoPhVrDLTCAmQWLQnFnL1dQAGRpHryvVv03ij8O0/c1PWAcaSAD3IaYs0QmuqtGG8X6AQOb5ol4TNPYfAZNhqr+wPojmBrgN/KLbVf7kEd7KfQrgy9jAA2hxGl1qLY2xshzxb845cMVdb2uA1sad08gz3mlYeW22G49GDiznELC0LGRr9huyrwVTzpBiVk1e4jBus3vC2t+vdzOrNPyNCOqyEC1/X3/ZqTQjlHJ6s6LiEpdLsZLsM2vk6zhz5jwnbw8qEerA0zw6Nh2w576TR58ijXQz7zhr5Q2EJ80CYqfRmzVdbBLp7yLkopuVGfpbAlm0Wl68yV2ETOK4L2ApVwC6iKzXLaGCG2494bvUl6htWhXVAczKkjdezF2/Y9p/ttxnwqO7wQjz+Qb2pB4vrmLXy7NxLzAK6RNxpu4M5qXTbQc/XlqKX3rcj8WryXZrWV9if2kAkgp3UeFApUEGFm7RkHY2wOofRlaQtYhTrfVjQ6uNOqo+r2ihwne3VtF1L6aKXRu5nIl+o5ha59D71xhvTqHBe4ogYIysKA/fpyDckWbnDF6/MCorFD4VXRVnEKTzgmz8QSWDaRW0hBKSWG+Uw8CtwHfK6GeWekKKpevag=
  # REGISTRY_TOKEN slug=gaztarifreglemente editor=cozy space=default
  - secure: W7l0rapUA7EW40KgXfLHbFT3tZF7USOy7nhUSdW/5Ah9IDgfzjFao+cfG0oZgqUvvjkwo7xKZTyT1DisqikbiGlxBaubt2gwrUOUdFbz6t0UMzkKa5Z0HA9jmUgldhVfNV/KGXCvlXILq5p2ilrvPd+xXYcMDaiHq3UDp/bZQYNSmxgc+Fy98Odo7dDJY3FKGJtzyocdqS9ND4lKJE3TaH79JMsXKM148bG5x3xVPmknqSBEAZOMy+cXjig3Z1YmtiiKT19no5FJIeQVbtq8yC0Z/OVaYu9GPciuuhO0GxFMFRWP3jCkD8TV8ID2OUD7GDNSa1clVVeZwfWYJJg77Eq91cRG3U6wjNcmWDeLE7eRYREunfPxsLEHx30a6rFvTZufd6ddoiMv79e156TPZBsRoJfpP1W5V2du+8REN2cd3EiqzYTcbWhBTDs6Ckuv1ByR31rJ00dTHGdm6xEQ6na/soS0/F9MYiBIV+diXAH+dhSLE6fkdn5wRtBOwaFduZ4flST5ifQbQE/yZFAHKeGM2UnLhXyR5JMUYSmFPpkkfhrAl2f5BrDhEJAy6CwOKHdDpHvSOkjMYvJVntk2lf3n0ub49EaYTorGjN4jA4zRaXK3uYbBhODCskNahVw4S6k6QkMZtg6LhdSC99Vx6N6Jewjh7rV57sdFoNqqzCI=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch:
    - master
    - main
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- if [[ -f /tmp/github_deploy_key ]]; then chmod 600 /tmp/github_deploy_key; fi
- if [[ -f /tmp/github_deploy_key ]]; then ssh-add /tmp/github_deploy_key; fi
after_deploy:
- rm -f /tmp/github_deploy_key
- ssh-add -D
